### PR TITLE
feat: add commitlint package

### LINKED ISSUE #120: Add Commitlint to packages to enforce commit style for semantic release

### PR DESCRIPTION
**Pull request by ankiiitraj**
close #120

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Hi @zenweasel!
Can you please review this PR. Thankyou!

**Comment by brent-hoover** [comment]
@ankiiitraj This implementation would require all users to run the `prepare` command before the commitlint would come into effect. We need to it to automatically be implemented like it is in our other projects.

**Comment by brent-hoover** [comment]
@ankiiitraj Nevermind, my mistake

**Comment by ankiiitraj** [comment]
We need to change `core.hooksPath` to `.husky`. I am searching for a way to update the path var automatically. But I am not able to find a way.

Rn, this will be enforced for the new people doing an `npm install`. But to enforce this for people who already have a copy, I will try to find a way.

**Comment by brent-hoover** [comment]
I think this is fine as it is. It's only for people who actually work on the package, not for those who use it.

**Review by brent-hoover — APPROVED** [review]

**Pull request merged**
