### PR TITLE
patch: use latest docker image for reaction

### LINKED ISSUE #130: Pull docker version from docker hub
When you create a new project-api the docker file that is used from the project template has a hardcoded reaction version. It should pull whatever is the the latest version number at the time of project creation from docker hub and use that instead. For deterministic builds we DO NOT want to use `:latest`

### PR DESCRIPTION
**Pull request by ankiiitraj**
close #130

### CODE REVIEW

**Comment by ankiiitraj** [comment]
@zenweasel Please have a look at this PR 😄

**Comment by brent-hoover** [comment]
@ankiiitraj No this isn't what we want. We want the Dockerfile pinned to whatever was the current version at project creation.

**Review by brent-hoover — CHANGES_REQUESTED** [review]
Needs to more closely follow the instructions in the issue

**Comment by brent-hoover** [comment]
Closing due to inactivity

**Pull request closed without merging**
